spring:
  jackson:
    parser:
      allow-backslash-escaping-any-character: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: adi
    password: 123
    driverClassName: oracle.jdbc.driver.OracleDriver

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: daw09.2022@gmail.com
    password: aanpxjgjbzoulmbu
